title: Rajesh HPC Portfolio
description: >- 
  15+ years in HPC | Academia, Pharma, Aviation | askhpc.pro
url: "https://askhpc.pro"
baseurl: ""  # Keep it blank for root deployment
author:
  name: "Rajesh Kumar"
  email: "your_email@example.com"
